strictness: high
test-warnings: true
doc-warnings: false

ignore-paths:
  - scripts
  - tests
  - skel_metamodel
  - main.py
  - main2.py

pep8:
  options:
    max-line-length: 100

mccabe:
  run: true
